version: "3.7"

services:
  auth_db:
    build:
      context: ./services/auth/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=auth_user
    volumes:
      - ./services/auth/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - auth_db
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --log-config logger.yml
    volumes:
      - ./services/auth:/app
    environment:
      - DOCKER=1
    env_file:
      - config.docker.env
      - config.auth.env


  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth
