version: "3.7"

services:
  auth_db:
    build:
      context: ./services/auth/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=auth_user
    volumes:
      - ./services/auth/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - auth_db
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --log-config logger.yml
    volumes:
      - ./services/auth:/app
    environment:
      - DOCKER=1

  worker:
    build: ./services/auth
    command: poetry run celery -A tasks.celery worker -l INFO
    volumes:
      - ./services/auth:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOCKER=1
      - TESTS=0
    depends_on:
      - auth_db
      - auth
      - redis

  redis:
    image: redis
