version: "3.7"

services:
  postgres:
    build:
      context: ./services/auth/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=auth_user
    volumes:
      - ./services/auth/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./services/auth:/app
    environment:
      - DOCKER=1
