version: "3.7"

services:
  auth_db:
    build:
      context: ./services/auth/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=auth_user
    volumes:
      - ./services/auth/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  main_db:
    build:
      context: ./services/main/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=main_user
    volumes:
      - ./services/main/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5434"

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - auth_db

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - auth_db
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --log-config logger.yml
    volumes:
      - ./services/auth:/app
    environment:
      - DOCKER=1

  main:
    build:
      context: ./services/main
      dockerfile: Dockerfile
    depends_on:
      - main_db
      - auth
      - auth_db
    ports:
      - "8001:8001"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --log-config logger.yml
    volumes:
      - ./services/main:/app
    environment:
      - DOCKER=1

  worker:
    build: ./services/auth
    command: poetry run celery -A tasks.celery worker -l INFO
    volumes:
      - ./services/auth:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOCKER=1
      - TESTS=0
    depends_on:
      - auth_db
      - auth
      - redis

  redis:
    image: redis
