version: "3.7"

services:
  auth_db:
    build:
      context: ./services/auth/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=auth_user
    volumes:
      - ./services/auth/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  main_db:
    build:
      context: ./services/main/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=main_user
    volumes:
      - ./services/main/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5434"

  email_db:
    build:
      context: ./services/email/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=email_user
    volumes:
      - ./services/email/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5435"

  messenger_db:
    build:
      context: ./services/messenger/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=messenger_user
    volumes:
      - ./services/messenger/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5436"

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - auth_db
      - main_db
      - email_db
      - messenger_db

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - auth_db
      - email
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --log-config logger.yml
    volumes:
      - ./services/auth:/app
    environment:
      - DOCKER=1

  main:
    build:
      context: ./services/main
      dockerfile: Dockerfile
    depends_on:
      - main_db
      - auth
    ports:
      - "8001:8001"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --log-config logger.yml
    volumes:
      - ./services/main:/app
    environment:
      - DOCKER=1

  email:
    build:
      context: ./services/email
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8003 --log-config logger.yml
    depends_on:
      - worker
    volumes:
      - ./services/email:/app
    environment:
      - DOCKER=1

  messenger:
    build:
      context: ./services/messenger
      dockerfile: Dockerfile
    depends_on:
      - main
      - messenger_db
    ports:
      - "8002:8002"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8002 --log-config logger.yml
    volumes:
      - ./services/messenger:/app
    environment:
      - DOCKER=1

  worker:
    build: ./services/email
    command: poetry run celery -A tasks.celery worker -l INFO
    volumes:
      - ./services/email:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOCKER=1
    depends_on:
      - redis
      - email_db

  dashboard:
    build: ./services/email
    command: poetry run celery flower --app=tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - ./services/email:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOCKER=1
    depends_on:
      - worker

  redis:
    image: redis
